### PR TITLE
refactor(icon-pos): icon-left/right to icon-start/end

### PR DESCRIPTION
**Pull request by danielsogl**
Merge it with the next release

https://github.com/ionic-team/ionic/pull/11912

### CODE REVIEW

**Comment by brandyscarney** [comment]
This was also in the latest nightly if we want to update to that. :smile:

**Comment by danielsogl** [comment]
@brandyscarney nah :D Better wait for the release :P

**Comment by danielsogl** [comment]
@jgw96 You should merge it to match the latest changes in Ionic 3.4

**Comment by brandyscarney** [comment]
Thanks Daniel, looks great 👍

**Pull request merged**
